  - name: "Step 5 - Assign Compute Hosts"
    shell: /var/lib/contrail_cloud/scripts/compute-nodes-assign.sh -d
    async: 3600
    poll: 0
    become_user: contrail
    register: result_assign_compute

  - name: "Step 5 - Wait for asynchronous job compute-nodes-assign.sh to finish" 
    async_status:
      jid: '{{ result_assign_compute.ansible_job_id }}'
    register: job_result
    until: job_result.finished
    retries: 10
    delay: 360
  
  - name: "Step 5 - Print execution result of compute-nodes-assign.sh"
    debug: var=result_assign_compute.stdout_lines