  - name: "Step 6 - Assign Storage Hosts"
    shell: /var/lib/contrail_cloud/scripts/storage-nodes-assign.sh -d
    async: 3600
    poll: 0
    become_user: contrail
    register: result_assign_storage

  - name: "Step 6 - Wait for asynchronous job storage-nodes-assign.sh to finish" 
    async_status:
      jid: '{{ result_assign_storage.ansible_job_id }}'
    register: job_result
    until: job_result.finished
    retries: 10
    delay: 360
  
  - name: "Step 6 - Print execution result of storage-nodes-assign.sh"
    debug: var=result_assign_storage.stdout_lines