  - name: "Render original configuration from Jinja2 template"
    template:
      src: "{{ leaf_cleanup_template }}/revert_config.j2"
      dest: "{{ build_dir }}/revert_config.conf"

  - name: "Load the rendered original configuration and commit"
    juniper_junos_config:
      src: "{{ build_dir }}/revert_config.conf"
      logfile: "{{ log_dir }}/revert_leaf_config_log"
      timeout: 120
      ignore_warning: true
      load: set
      format: text
      check_commit_wait: 4
      check: true
      commit: true
    register: response